#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "Season42 BFF — Azure setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Azure — confirm the subscription"
say "Everything below is created in one Azure subscription. Let's agree which."
if ! command -v az >/dev/null 2>&1; then
  warn "the Azure CLI is not installed."
  say "Install it, then re-run:  brew install azure-cli"
  exit 1
fi
if ! az account show >/dev/null 2>&1; then
  warn "you are not logged in to Azure."
  say "Log in in another terminal, then re-run this script:"
  say "  az login"
  exit 1
fi
AZ_NAME=$(az account show --query name -o tsv)
AZURE_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
AZURE_TENANT_ID=$(az account show --query tenantId -o tsv)
AZ_USER=$(az account show --query user.name -o tsv)
say ""
say "  subscription : $AZ_NAME"
say "  id           : $AZURE_SUBSCRIPTION_ID"
say "  signed in as : $AZ_USER"
say ""
if ! confirm "Create everything in this subscription?"; then
  say "Switch with:  az account set --subscription <name-or-id>"
  say "Then re-run this script."
  exit 1
fi
write_env AZURE_SUBSCRIPTION_ID "$AZURE_SUBSCRIPTION_ID"
write_env AZURE_TENANT_ID "$AZURE_TENANT_ID"
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Azure — resource providers"
say "A subscription must opt in to each Azure service before it can be used."
say "Microsoft.App is the Container Apps provider; the others back the registry,"
say "the file share, and the logs the environment writes to."
note "Registering something already registered does nothing. This can take a few minutes."
say ""
for provider in Microsoft.App Microsoft.ContainerRegistry Microsoft.Storage Microsoft.OperationalInsights; do
  state=$(az provider show -n "$provider" --query registrationState -o tsv 2>/dev/null || echo "Unknown")
  if [[ "$state" == "Registered" ]]; then
    say "  $provider — already registered"
  else
    say "  $provider — registering, please wait..."
    az provider register -n "$provider" --wait
    say "  $provider — registered"
  fi
done
if ! az containerapp --help >/dev/null 2>&1; then
  say ""
  say "Installing the containerapp CLI extension..."
  az extension add --name containerapp --upgrade --yes
fi
say ""
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Azure — resource group"
say "The resource group holds everything: the registry, the storage account,"
say "the Container Apps environment, and the app itself. Deleting it deletes all"
say "of them, which is the point — it is the unit you can throw away."
say ""
ask AZURE_RESOURCE_GROUP "Resource group name [season42]:"
AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP:-season42}
ask AZURE_LOCATION "Region [norwayeast]:"
AZURE_LOCATION=${AZURE_LOCATION:-norwayeast}
say ""
if az group show -n "$AZURE_RESOURCE_GROUP" >/dev/null 2>&1; then
  existing_location=$(az group show -n "$AZURE_RESOURCE_GROUP" --query location -o tsv)
  say "Resource group '$AZURE_RESOURCE_GROUP' already exists in $existing_location — leaving it alone."
  AZURE_LOCATION="$existing_location"
else
  say "Creating resource group '$AZURE_RESOURCE_GROUP' in $AZURE_LOCATION..."
  az group create -n "$AZURE_RESOURCE_GROUP" -l "$AZURE_LOCATION" -o none
  say "Created."
fi
write_env AZURE_RESOURCE_GROUP "$AZURE_RESOURCE_GROUP"
write_env AZURE_LOCATION "$AZURE_LOCATION"
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Azure — Container Apps environment"
say "The environment is the substrate the BFF runs on: the private network its"
say "container sits in, and the edge that terminates TLS in front of it."
say ""
note "This is the slow one — creating it takes several minutes, and it brings a"
note "Log Analytics workspace with it. Leave it running."
say ""
ask AZURE_CONTAINERAPP_ENV "Environment name [season42-env]:"
AZURE_CONTAINERAPP_ENV=${AZURE_CONTAINERAPP_ENV:-season42-env}
say ""
if az containerapp env show -n "$AZURE_CONTAINERAPP_ENV" -g "$AZURE_RESOURCE_GROUP" >/dev/null 2>&1; then
  say "Environment '$AZURE_CONTAINERAPP_ENV' already exists — leaving it alone."
else
  say "Creating '$AZURE_CONTAINERAPP_ENV'. This takes a few minutes..."
  az containerapp env create \
    -n "$AZURE_CONTAINERAPP_ENV" \
    -g "$AZURE_RESOURCE_GROUP" \
    -l "$AZURE_LOCATION" \
    -o none
  say "Created."
fi
write_env AZURE_CONTAINERAPP_ENV "$AZURE_CONTAINERAPP_ENV"
say ""
note "The registry, storage account and file share are NOT created here — the"
note "Bicep template owns those, because they change when the app changes."
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "TMDB — the access token"
say "The BFF exists to keep this token off the phone. Without it the server"
say "refuses to start, deliberately — a server that starts without one would"
say "look healthy and answer every search with the same unexplained emptiness."
say ""
step "Log in to TMDB, then copy the API Read Access Token."
step "That is the long token — NOT the shorter, older 'API Key'."
open_url "https://www.themoviedb.org/settings/api"
say ""
ask_secret TMDB_ACCESS_TOKEN "Paste the API Read Access Token:"
if [[ -z "${TMDB_ACCESS_TOKEN:-}" ]]; then
  warn "no token entered — skipping. The BFF will not start without it."
  SKIPPED+=("TMDB access token (re-run this script, or set it manually)")
else
  write_env TMDB_ACCESS_TOKEN "$TMDB_ACCESS_TOKEN"
  set_secret TMDB_ACCESS_TOKEN "$TMDB_ACCESS_TOKEN"
fi
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Entra — an identity for GitHub Actions"
say "So that CI can deploy without a password existing anywhere. GitHub proves"
say "who it is with a short-lived token Azure trusts, scoped to this repository"
say "and the main branch — nothing else can use it."
say ""
DEFAULT_REPO=""
if command -v gh >/dev/null 2>&1; then
  DEFAULT_REPO=$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo "")
fi
ask GITHUB_REPO "GitHub repository, owner/name${DEFAULT_REPO:+ [$DEFAULT_REPO]}:"
GITHUB_REPO=${GITHUB_REPO:-$DEFAULT_REPO}
if [[ -z "$GITHUB_REPO" ]]; then
  warn "no repository given — cannot scope the credential. Skipping this stage."
  SKIPPED+=("Entra app registration and federated credential")
else
  write_env GITHUB_REPO "$GITHUB_REPO"
  APP_NAME="season42-bff-deploy"
  say ""
  AZURE_CLIENT_ID=$(az ad app list --display-name "$APP_NAME" --query "[0].appId" -o tsv 2>/dev/null || echo "")
  if [[ -n "$AZURE_CLIENT_ID" ]]; then
    say "App registration '$APP_NAME' already exists — reusing it."
  else
    say "Creating the app registration '$APP_NAME'..."
    if ! AZURE_CLIENT_ID=$(az ad app create --display-name "$APP_NAME" --query appId -o tsv 2>/dev/null); then
      AZURE_CLIENT_ID=""
    fi
  fi

  if [[ -z "$AZURE_CLIENT_ID" ]]; then
    warn "could not create an app registration."
    say "This is almost always a permissions problem, not a bug: your Entra tenant"
    say "may not let this account register applications."
    say ""
    step "Ask a tenant administrator to create an app registration named '$APP_NAME',"
    step "or to grant you the Application Developer role, then re-run this script."
    SKIPPED+=("Entra app registration '$APP_NAME' and its federated credential")
  else
    say "Client id: $AZURE_CLIENT_ID"
    write_env AZURE_CLIENT_ID "$AZURE_CLIENT_ID"

    az ad sp show --id "$AZURE_CLIENT_ID" >/dev/null 2>&1 || \
      az ad sp create --id "$AZURE_CLIENT_ID" -o none

    # Two credentials, one branch. GitHub is moving the `sub` claim from names to immutable
    # numeric ids — `repo:owner@<owner id>/repo@<repo id>:ref:...` — and which form a run presents
    # is GitHub's call, not ours. A credential matching only the name form fails the day the
    # rollout reaches this repository, with an error that reads like a misconfigured subject. So
    # both forms are registered; a token matches exactly one of them and the other sits unused.
    CRED_SUBJECTS=("github-main|repo:$GITHUB_REPO:ref:refs/heads/main")
    if command -v gh >/dev/null 2>&1; then
      # The ids come from the repository itself; there is no way to derive them from the name.
      REPO_IDS=$(gh api "repos/$GITHUB_REPO" --jq '"\(.owner.login)@\(.owner.id)/\(.name)@\(.id)"' 2>/dev/null || echo "")
      if [[ -n "$REPO_IDS" ]]; then
        CRED_SUBJECTS+=("github-main-immutable|repo:$REPO_IDS:ref:refs/heads/main")
      else
        warn "could not read $GITHUB_REPO's numeric ids from GitHub — registering only the"
        warn "name-form subject. If a deploy later fails with 'No matching federated identity"
        warn "record', add a credential for the subject the error reports."
      fi
    fi
    for CRED in "${CRED_SUBJECTS[@]}"; do
      CRED_NAME=${CRED%%|*}
      CRED_SUBJECT=${CRED#*|}
      if az ad app federated-credential show --id "$AZURE_CLIENT_ID" --federated-credential-id "$CRED_NAME" >/dev/null 2>&1; then
        say "Federated credential '$CRED_NAME' already exists — leaving it alone."
        continue
      fi
      say "Adding federated credential '$CRED_NAME' for $CRED_SUBJECT..."
      CRED_FILE=$(mktemp)
      cat > "$CRED_FILE" <<CREDENTIAL
{
  "name": "$CRED_NAME",
  "issuer": "https://token.actions.githubusercontent.com",
  "subject": "$CRED_SUBJECT",
  "description": "Deploys the Season42 BFF from the main branch",
  "audiences": ["api://AzureADTokenExchange"]
}
CREDENTIAL
      az ad app federated-credential create --id "$AZURE_CLIENT_ID" --parameters "@$CRED_FILE" -o none
      rm -f "$CRED_FILE"
      say "Added."
    done
    note "Only pushes to main can use this identity. Pull requests run the tests"
    note "and never touch Azure, so they need no credential at all."
  fi
fi
pause "Press Enter to continue"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Azure — let that identity deploy"
say "The identity exists but can do nothing yet. This grants it two roles on the"
say "resource group only — it can manage what is inside '$AZURE_RESOURCE_GROUP'"
say "and nothing anywhere else in the subscription."
say ""
say "Contributor covers the deployment itself. The second role exists because the"
say "template gives the container app's identity AcrPull on the registry, and"
say "writing a role assignment is not something Contributor may do. It is granted"
say "under a condition that allows AcrPull and no other role, so CI cannot widen"
say "its own access with it."
say ""
# The AcrPull role's fixed definition id, the same one infra/main.bicep assigns.
ACR_PULL_ROLE_ID="7f951dda-4ed3-4680-a7ca-43fe172d538d"
# Reads as: any write must be AcrPull, and any delete must be of an AcrPull assignment. Every
# other action the role carries is untouched by the condition.
ACR_PULL_ONLY_CONDITION="((!(ActionMatches{'Microsoft.Authorization/roleAssignments/write'})) OR (@Request[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{$ACR_PULL_ROLE_ID})) AND ((!(ActionMatches{'Microsoft.Authorization/roleAssignments/delete'})) OR (@Resource[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals{$ACR_PULL_ROLE_ID}))"
if [[ -z "${AZURE_CLIENT_ID:-}" ]]; then
  warn "no identity was created in the previous stage — nothing to grant."
  SKIPPED+=("Contributor and RBAC Administrator role assignments on $AZURE_RESOURCE_GROUP")
else
  SCOPE="/subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/$AZURE_RESOURCE_GROUP"
  for ROLE in "Contributor" "Role Based Access Control Administrator"; do
    EXISTING=$(az role assignment list --assignee "$AZURE_CLIENT_ID" --scope "$SCOPE" \
      --query "[?roleDefinitionName=='$ROLE'] | length(@)" -o tsv 2>/dev/null || echo "0")
    ROLE_ARGS=(--assignee "$AZURE_CLIENT_ID" --role "$ROLE" --scope "$SCOPE")
    CONDITION_HINT=""
    if [[ "$ROLE" != "Contributor" ]]; then
      ROLE_ARGS+=(--condition "$ACR_PULL_ONLY_CONDITION" --condition-version "2.0")
      CONDITION_HINT=" (AcrPull only)"
    fi
    say ""
    if [[ "$EXISTING" != "0" ]]; then
      say "'$ROLE'$CONDITION_HINT already granted — leaving it alone."
    elif confirm "Grant '$ROLE'$CONDITION_HINT on '$AZURE_RESOURCE_GROUP' to the deploy identity?"; then
      if az role assignment create "${ROLE_ARGS[@]}" -o none 2>/dev/null; then
        say "Granted."
      else
        warn "could not create the '$ROLE' role assignment."
        say "Granting a role needs Owner or User Access Administrator on the resource"
        say "group. Ask someone who has it to run:"
        say ""
        say "  az role assignment create --assignee $AZURE_CLIENT_ID \\"
        if [[ "$ROLE" == "Contributor" ]]; then
          say "    --role \"$ROLE\" --scope $SCOPE"
        else
          say "    --role \"$ROLE\" --scope $SCOPE \\"
          say "    --condition-version 2.0 --condition \"$ACR_PULL_ONLY_CONDITION\""
        fi
        SKIPPED+=("$ROLE role assignment on $AZURE_RESOURCE_GROUP")
      fi
    else
      say "Skipped. CI cannot deploy until this is granted."
      SKIPPED+=("$ROLE role assignment on $AZURE_RESOURCE_GROUP")
    fi
  done
fi
pause "Press Enter to continue"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "GitHub — hand the values to CI"
say "The deploy workflow reads these. Ids and the token go in as secrets; names"
say "and the region go in as variables, because they are not worth hiding and"
say "are easier to read in a log when a deploy goes wrong."
say ""
set_secret AZURE_SUBSCRIPTION_ID "$AZURE_SUBSCRIPTION_ID"
set_secret AZURE_TENANT_ID "$AZURE_TENANT_ID"
if [[ -n "${AZURE_CLIENT_ID:-}" ]]; then
  set_secret AZURE_CLIENT_ID "$AZURE_CLIENT_ID"
else
  SKIPPED+=("GitHub secret AZURE_CLIENT_ID (no identity was created)")
fi
set_var AZURE_RESOURCE_GROUP "$AZURE_RESOURCE_GROUP"
set_var AZURE_LOCATION "$AZURE_LOCATION"
set_var AZURE_CONTAINERAPP_ENV "$AZURE_CONTAINERAPP_ENV"
say ""
note "TMDB_ACCESS_TOKEN was set earlier, in the TMDB stage."
pause "Press Enter to finish"

finish
